name: "Set Status and Run Command"
description: "Sets a status on HEAD, runs a command, and updates status based on success or failure"
author: "Vercel"
inputs:
  status-name:
    description: "The context name for the status"
    required: true
  command:
    description: "The command to run"
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
