name: "Set Status and Run Command"
description: "Sets a status on HEAD, runs a command, and updates status based on success or failure"
author: "Vercel"
inputs:
  status-name:
    description: "The context name for the status"
    required: true
  command:
    description: "The command to run"
    required: true
  checkout-path:
    description: "The path to checkout the repository to"
    required: false
  checkout-fetch-depth:
    description: "Number of commits to fetch. 0 indicates all history for all branches and tags"
    required: false
    default: "1"
runs:
  using: "node20"
  main: "dist/index.js"
