name: "Vercel Checkout"
description: "Checkout for Vercel deployment events. Automatically checks out the ref from the SHA of the deployment."
inputs:
  ref:
    description: "The branch, tag or SHA to checkout"
    required: false
  lfs:
    description: "Whether to download Git LFS files"
    required: false
  fetch-depth:
    description: "Number of commits to fetch. 0 for full history."
    required: false
  token:
    description: "The token to use for fetching"
    required: false
    default: "${{ github.token }}"
  filter:
    description: "Sparse checkout filter"
    required: false

runs:
  using: "composite"
  steps:
    - name: Determine ref
      id: determine-ref
      shell: bash
      run: |
        # Set environment variables for the script
        export GITHUB_EVENT_NAME="${{ github.event_name }}"
        export GITHUB_EVENT_CLIENT_PAYLOAD_GIT_SHA="${{ github.event.client_payload.git.sha }}"

        # Call the script and capture output
        output=$(./actions/checkout/scripts/determine-ref.sh "${{ inputs.ref }}")

        # Extract the ref value and set it as output
        ref=$(echo "$output" | grep "^ref=" | cut -d'=' -f2-)
        echo "ref=$ref" >> "$GITHUB_OUTPUT"

        # Print the status message (lines that don't start with ref=)
        echo "$output" | grep -v "^ref=" || true

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.determine-ref.outputs.ref }}
        lfs: ${{ inputs.lfs }}
        fetch-depth: ${{ inputs.fetch-depth }}
        token: ${{ inputs.token }}
        filter: ${{ inputs.filter }}
