name: 'Vercel Repository Dispatch - Debug'
description: 'Debug action for Vercel repository dispatch deployment events. Useful for viewing the full payload from the event.'

runs:
  using: 'composite'
  steps:
    - name: Debug Client Payload
      shell: bash
      run: |
        echo "🔍 Debugging Vercel Repository Dispatch Client Payload"
        echo ""

        # Check if this is a repository_dispatch event
        if [[ "${{ github.event_name }}" != "repository_dispatch" ]]; then
          echo "❌ This action is designed for repository_dispatch events only."
          echo "📋 Current event type: ${{ github.event_name }}"
          exit 0
        fi

        echo "✅ Event type: ${{ github.event_name }}"
        echo ""

        # Output the full client payload in a collapsible section
        echo "::group::📦 Full Client Payload (Click to expand)"
        echo '${{ toJSON(github.event.client_payload) }}'
        echo "::endgroup::"
        echo ""

        # Output individual fields with emoji prefixes
        echo "::group::🏗️ Project Information"
        echo "📝 Project Name: ${{ github.event.client_payload.project.name || 'N/A' }}"
        echo "🆔 Project ID: ${{ github.event.client_payload.project.id || 'N/A' }}"
        echo "::endgroup::"
        echo ""

        echo "::group::🌍 Environment"
        echo "🌱 Environment: ${{ github.event.client_payload.environment || 'N/A' }}"
        echo "::endgroup::"
        echo ""

        echo "::group::📚 Git Information"
        echo "🌿 Git Ref: ${{ github.event.client_payload.git.ref || 'N/A' }}"
        echo "🔗 Git SHA: ${{ github.event.client_payload.git.sha || 'N/A' }}"
        echo "✂️ Short SHA: ${{ github.event.client_payload.git.shortSha || 'N/A' }}"
        echo "::endgroup::"
        echo ""

        echo "::group::🚀 Deployment Information"
        echo "🌐 Deployment URL: ${{ github.event.client_payload.url || 'N/A' }}"
        echo "🆔 Deployment ID: ${{ github.event.client_payload.id || 'N/A' }}"
        echo "::endgroup::"
        echo ""

        echo "::group::📊 State Information"
        echo "📈 State Type: ${{ github.event.client_payload.state.type || 'N/A' }}"
        echo "📋 State Detail: ${{ github.event.client_payload.state.detail || 'N/A' }}"
        echo "::endgroup::"
        echo ""

        # Check for error information
        if [[ -n "${{ github.event.client_payload.error }}" ]]; then
          echo "::group::❌ Error Information"
          echo "💥 Error: ${{ github.event.client_payload.error }}"
          echo "::endgroup::"
          echo ""
        fi

        echo "🎉 Debug output complete!"
