name: Test Action with Repository Dispatch

on:
  repository_dispatch:
    types:
      - vercel.deployment.success

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - uses: ./actions/status
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Action that failes
        run: |
          echo "This is a test"
          exit 1

      - name: Action that passes
        run: |
          echo "This is a test"
          exit 0
